/* =========================================================
   بيانات المتجر — نسخة العرض المحلية (Fallback)
   =========================================================
   تُستخدم هذه البيانات فقط عند تعذّر الوصول للخادم الخلفي (معاينة
   ثابتة بلا backend، أو انقطاع اتصال). عند توفّر الخادم، تُستبدل هذه
   المصفوفات تلقائيًا ببيانات حقيقية من قاعدة البيانات (انظر js/api.js).
   - لتغيير صورة منتج: استبدل قيمة "icon" باسم أيقونة من ملف icons.js
     أو استبدلها بوسم <img src="مسار-صورتك.jpg"> داخل js/main.js
   - لتغيير السعر: عدّل "price" (بالريال السعودي)
   - لإضافة منتج جديد: انسخ كائن منتج كامل وغيّر id و slug إلى قيمتين فريدتين
   ========================================================= */

const STORE = {
  currency: "ر.س",
  whatsapp: "966500000000" // رقم واتساب المتجر للاستفسار عن الأسعار
};

let PRODUCTS = [
  {
    id: 1,
    slug: "chinese-vase-1",
    title: "مزهرية صينية مطلية يدويًا",
    titleEn: "Hand-Painted Chinese Porcelain Vase",
    category: "مزهريات",
    categoryEn: "Vases & Ceramics",
    categorySlug: "vases",
    era: "أواخر القرن التاسع عشر",
    origin: "الصين",
    material: "خزف مطلي بالذهب",
    condition: "ممتازة — ترميم طفيف بالقاعدة",
    price: 18500,
    oldPrice: 22000,
    image: "images/products/product-1.jpg",
    icon: "vase",
    badge: "قطعة نادرة",
    description: "مزهرية خزفية أصلية بزخارف يدوية دقيقة تعود لأواخر القرن التاسع عشر، برسومات تقليدية من الطيور وأزهار اللوتس، وتفاصيل مذهّبة على الحواف.",
    descriptionEn: "An authentic porcelain vase with fine hand-painted decoration from the late 19th century, featuring traditional bird and lotus motifs with gilded edge detailing.",
    stock: 1
  },
  {
    id: 2,
    slug: "french-chandelier",
    title: "ثريا كريستال فرنسية",
    titleEn: "French Crystal Chandelier",
    category: "إضاءة",
    categoryEn: "Antique Lighting",
    categorySlug: "lighting",
    era: "حقبة آرت ديكو 1920",
    origin: "فرنسا",
    material: "كريستال وبرونز مذهّب",
    condition: "جيدة جدًا — كامل القطع الأصلية",
    price: 42000,
    oldPrice: null,
    image: "images/products/product-2.jpg",
    icon: "chandelier",
    badge: "توثيق أصلي",
    description: "ثريا فاخرة من حقبة آرت ديكو، مكوّنة من بلورات كريستال مقطوعة يدويًا على هيكل برونزي مذهّب، بحالة أصلية نادرة تحمل توقيع الصانع.",
    descriptionEn: "A luxurious Art Deco-era chandelier featuring hand-cut crystal on a gilded bronze frame, in rare original condition bearing the maker's mark.",
    stock: 1
  },
  {
    id: 3,
    slug: "rococo-mirror",
    title: "مرآة مؤطرة بالذهب الروكوكو",
    titleEn: "Gold Rococo Framed Mirror",
    category: "مرايا",
    categoryEn: "Framed Mirrors",
    categorySlug: "mirrors",
    era: "القرن الثامن عشر",
    origin: "إيطاليا",
    material: "خشب منحوت مذهّب وزجاج أصلي",
    condition: "أصلية بالكامل",
    price: 31500,
    oldPrice: 36000,
    image: "images/products/product-3.jpg",
    icon: "mirror",
    badge: "مقتنى المتاحف",
    description: "مرآة بإطار خشبي منحوت يدويًا بطراز الروكوكو الإيطالي، مغطى بورق الذهب الأصلي، بزجاج عتيق يحمل بصمات الزمن المميزة.",
    descriptionEn: "A hand-carved wooden mirror frame in the Italian Rococo style, covered in original gold leaf, with antique glass bearing the distinctive marks of time.",
    stock: 1
  },
  {
    id: 4,
    slug: "victorian-clock",
    title: "ساعة طاولة برونزية فيكتورية",
    titleEn: "Victorian Bronze Table Clock",
    category: "ساعات",
    categoryEn: "Clocks",
    categorySlug: "clocks",
    era: "منتصف القرن التاسع عشر",
    origin: "إنجلترا",
    material: "برونز وميناء رخامي",
    condition: "تعمل بآلية أصلية مجددة",
    price: 15200,
    oldPrice: null,
    image: "images/products/product-4.jpg",
    icon: "clock",
    badge: null,
    description: "ساعة طاولة برونزية من الحقبة الفيكتورية، بآلية ميكانيكية أصلية أعيد ضبطها من قبل خبراء الساعات الأثرية، وقاعدة رخامية منحوتة.",
    descriptionEn: "A Victorian-era bronze table clock with an original mechanical movement restored by antique clock specialists, set on a carved marble base.",
    stock: 2
  },
  {
    id: 5,
    slug: "greek-statue",
    title: "تمثال رخامي إغريقي الطراز",
    titleEn: "Greek-Style Marble Statue",
    category: "منحوتات",
    categoryEn: "Sculptures & Statues",
    categorySlug: "sculptures",
    era: "إحياء كلاسيكي، القرن التاسع عشر",
    origin: "اليونان",
    material: "رخام كرارا",
    condition: "ممتازة",
    price: 27800,
    oldPrice: null,
    image: "images/products/product-5.jpg",
    icon: "statue",
    badge: "قطعة نادرة",
    description: "منحوتة رخامية على الطراز الإغريقي الكلاسيكي، منحوتة يدويًا من رخام كرارا الإيطالي الفاخر، بتفاصيل دقيقة تعكس براعة النحت الكلاسيكي.",
    descriptionEn: "A classical Greek-style marble sculpture, hand-carved from fine Italian Carrara marble, with intricate detailing reflecting masterful classical craftsmanship.",
    stock: 1
  },
  {
    id: 6,
    slug: "damascus-jewelry-box",
    title: "صندوق مجوهرات مطعّم بالصدف",
    titleEn: "Mother-of-Pearl Inlaid Jewelry Box",
    category: "صناديق",
    categoryEn: "Boxes & Chests",
    categorySlug: "boxes",
    era: "أوائل القرن العشرين",
    origin: "دمشق",
    material: "خشب الجوز وطعمية الصدف",
    condition: "أصلية — بطانة مخملية مستبدلة",
    price: 6400,
    oldPrice: 7900,
    image: "images/products/product-6.jpg",
    icon: "chest",
    badge: null,
    description: "صندوق مجوهرات دمشقي تقليدي، مطعّم بالصدف والعرق بزخارف هندسية متقنة، من أعمال الحرفيين الدمشقيين في أوائل القرن العشرين.",
    descriptionEn: "A traditional Damascene jewelry box inlaid with mother-of-pearl in intricate geometric patterns, crafted by Damascene artisans in the early 20th century.",
    stock: 3
  },
  {
    id: 7,
    slug: "french-oil-painting",
    title: "لوحة زيتية لمشهد ريفي",
    titleEn: "Oil Painting of a Countryside Scene",
    category: "لوحات",
    categoryEn: "Paintings",
    categorySlug: "paintings",
    era: "أواخر القرن التاسع عشر",
    origin: "فرنسا",
    material: "زيت على قماش، إطار خشبي مذهّب",
    condition: "مرممة باحترافية",
    price: 24900,
    oldPrice: null,
    image: "images/products/product-7.jpg",
    icon: "painting",
    badge: "توثيق أصلي",
    description: "لوحة زيتية أصلية تصوّر مشهدًا ريفيًا بأسلوب الانطباعية الفرنسية المبكرة، بإطار خشبي مذهّب أصلي من نفس الحقبة.",
    descriptionEn: "An original oil painting depicting a countryside scene in early French Impressionist style, in its original gilded wooden frame from the same era.",
    stock: 1
  },
  {
    id: 8,
    slug: "ivory-chess-set",
    title: "طقم شطرنج عاجي منحوت يدويًا",
    titleEn: "Hand-Carved Ivory Chess Set",
    category: "ألعاب فاخرة",
    categoryEn: "Luxury Games",
    categorySlug: "games",
    era: "القرن التاسع عشر",
    origin: "الهند",
    material: "عاج وأبنوس",
    condition: "كامل القطع 32/32",
    price: 19700,
    oldPrice: null,
    image: "images/products/product-8.jpg",
    icon: "chess",
    badge: null,
    description: "طقم شطرنج فاخر منحوت يدويًا بتفاصيل بالغة الدقة، القطع البيضاء من العاج الطبيعي والسوداء من خشب الأبنوس، بحالة كاملة ونادرة.",
    descriptionEn: "A luxurious hand-carved chess set with extremely fine detail — white pieces in natural ivory and black pieces in ebony wood, complete and in rare condition.",
    stock: 1
  }
];

let AUCTIONS = [
  {
    id: 101,
    lot: "LOT 014",
    title: "خنجر مرصّع بالياقوت — العصر العثماني",
    titleEn: "Ruby-Encrusted Dagger — Ottoman Era",
    category: "أسلحة تراثية",
    categoryEn: "Heritage Weapons",
    image: "images/auctions/auction-101.jpg",
    icon: "dagger",
    startPrice: 12000,
    currentBid: 28500,
    bidsCount: 17,
    endsAt: Date.now() + 1000 * 60 * 60 * 26,
    status: "live",
    description: "خنجر عثماني نادر من أواخر القرن الثامن عشر، بمقبض مرصّع بأحجار الياقوت الطبيعي وزخارف فضية مطعّمة يدويًا على النصل والغمد.",
    descriptionEn: "A rare Ottoman dagger from the late 18th century, its handle set with natural ruby stones and hand-inlaid silver decoration on both blade and sheath."
  },
  {
    id: 102,
    lot: "LOT 015",
    title: "سجادة حريرية فارسية أصلية",
    titleEn: "Authentic Persian Silk Carpet",
    category: "سجاد فاخر",
    categoryEn: "Luxury Carpets",
    image: "images/auctions/auction-102.jpg",
    icon: "carpet",
    startPrice: 30000,
    currentBid: 52000,
    bidsCount: 24,
    endsAt: Date.now() + 1000 * 60 * 60 * 4,
    status: "live",
    description: "سجادة حريرية يدوية الحياكة من مدينة قُم الفارسية، بكثافة عقد فائقة الدقة وألوان طبيعية محفوظة بحالة استثنائية منذ أكثر من قرن.",
    descriptionEn: "A hand-woven silk carpet from the Persian city of Qom, with an exceptionally fine knot density and natural dyes preserved in outstanding condition for over a century."
  },
  {
    id: 103,
    lot: "LOT 016",
    title: "إبريق فضي منقوش — الحقبة المملوكية",
    titleEn: "Engraved Silver Ewer — Mamluk Era",
    category: "معادن ثمينة",
    categoryEn: "Precious Metalwork",
    image: "images/auctions/auction-103.jpg",
    icon: "vase",
    startPrice: 9000,
    currentBid: 15400,
    bidsCount: 11,
    endsAt: Date.now() + 1000 * 60 * 60 * 50,
    status: "live",
    description: "إبريق فضي بنقوش هندسية وكتابات كوفية مملوكية الطراز، من أعمال الحرفيين المهرة في القاهرة القديمة.",
    descriptionEn: "A silver ewer with geometric engravings and Kufic-style inscriptions in the Mamluk tradition, crafted by skilled artisans in old Cairo."
  },
  {
    id: 104,
    lot: "LOT 017",
    title: "خزانة عرض إنجليزية بالماهوجني",
    titleEn: "English Mahogany Display Cabinet",
    category: "أثاث فاخر",
    categoryEn: "Luxury Furniture",
    image: "images/auctions/auction-104.jpg",
    icon: "chest",
    startPrice: 20000,
    currentBid: 20000,
    bidsCount: 0,
    endsAt: Date.now() + 1000 * 60 * 60 * 96,
    status: "upcoming",
    description: "خزانة عرض إنجليزية من خشب الماهوجني الفاخر بواجهات زجاجية منحنية يدويًا، تعود لأوائل القرن العشرين.",
    descriptionEn: "An English display cabinet in fine mahogany with hand-curved glass fronts, dating to the early 20th century."
  },
  {
    id: 105,
    lot: "LOT 011",
    title: "قلادة ذهبية بأحجار الزمرد",
    titleEn: "Gold Necklace with Emerald Stones",
    category: "مجوهرات أثرية",
    categoryEn: "Antique Jewelry",
    image: "images/auctions/auction-105.jpg",
    icon: "necklace",
    startPrice: 40000,
    currentBid: 71000,
    bidsCount: 33,
    endsAt: Date.now() - 1000 * 60 * 60,
    status: "closed",
    description: "قلادة ذهبية عيار 21 مرصّعة بأحجار الزمرد الطبيعي، من تصميم متأثر بالحلي الملكية في أوائل القرن العشرين.",
    descriptionEn: "21-karat gold necklace set with natural emerald stones, in a design influenced by royal jewelry of the early 20th century."
  },
  {
    id: 106,
    lot: "LOT 018",
    title: "بيانو أثري مذهّب الحواف",
    titleEn: "Antique Piano with Gilded Edges",
    category: "آلات موسيقية",
    categoryEn: "Musical Instruments",
    image: "images/auctions/auction-106.jpg",
    icon: "piano",
    startPrice: 55000,
    currentBid: 55000,
    bidsCount: 0,
    endsAt: Date.now() + 1000 * 60 * 60 * 120,
    status: "upcoming",
    description: "بيانو نصف ذيلي أوروبي بحواف مذهّبة منحوتة يدويًا، آلية أصلية مجددة بالكامل من قبل خبراء ترميم الآلات الموسيقية.",
    descriptionEn: "A European baby grand piano with hand-carved gilded edges, its original mechanism fully restored by musical instrument restoration specialists."
  }
];
